// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqz9jNgFAghvt5tqqGsEmYsbZG62QqKXc',
    appId: '1:792129163047:web:2fd2fa07f2facfffe0a302',
    messagingSenderId: '792129163047',
    projectId: 'chat-app-9ae90',
    authDomain: 'chat-app-9ae90.firebaseapp.com',
    storageBucket: 'chat-app-9ae90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoECO1zeS60EzTsnTaBkE2vKeJ3rL6pJQ',
    appId: '1:792129163047:android:3fa54896561743d9e0a302',
    messagingSenderId: '792129163047',
    projectId: 'chat-app-9ae90',
    storageBucket: 'chat-app-9ae90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyDaCu5v8QFK2kmA_Fvhs7HFQfItXydNw',
    appId: '1:792129163047:ios:171df95fbd91c7d4e0a302',
    messagingSenderId: '792129163047',
    projectId: 'chat-app-9ae90',
    storageBucket: 'chat-app-9ae90.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
